# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4c207fafa70f0b770d0307e255d54a8da3a3934ae2adc7663712757dba2f2f9b4cd255aa1a67e8137705f3d86a2f5badd7afe139c517d6bf18e9b4443b3404d

test:
  secret_key_base: 9ff9f19e01c62f7bcbc813d9c3a05cc00548b2808b492ef0a4fc3c849ec382246c3a92c54fc8f8d36e9a8118ae493885d6cedf31f2409c0b97b5c371a94cd489

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

shared:
  github_username: stephenkey
  github_token: 9f9fea972d6ee2663ea1b573174f260e8d91f716
